# Generated by Django 5.1.4 on 2025-09-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0004_alter_profile_college_alter_profile_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_images/default.png', null=True, upload_to='profile_images/'),
        ),
    ]
