# Generated by Django 5.1.4 on 2025-09-14 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel', '0007_roombookingdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomBookingDetail',
        ),
    ]
